### ISSUE TITLE
SyntaxError: invalid syntax (Python 2.7)

### ISSUE THREAD

**Issue by ryan0802** [dahlia/wikidata#12]
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from wikidata.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Wikidata-0.6.1-py2.7.egg/wikidata/client.py", line 86
    base_url: str=WIKIDATA_BASE_URL,
            ^
SyntaxError: invalid syntax

**Comment by teolemon** [comment]
Just curious how you managed to run it on Python 2.7

**Comment by dahlia** [comment]
This project does not support Python 2, and has no plan to do, since [it will retire soon][1].

[1]: https://pythonclock.org/
