### ISSUE TITLE
ImportError: No module named 'wikidata' (Python 3.5)

### ISSUE THREAD

**Issue by ryan0802** [dahlia/wikidata#13]
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wikidata.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'wikidata'

**Comment by Ocuatrec** [comment]
Did you fix the error?

**Comment by ryan0802** [comment]
No, I don't know why. Please help.

**Comment by WolfgangFahl** [comment]
this looks like a pythonpath issue see e.g. https://stackoverflow.com/questions/23417941/python-import-error-no-module-named-does-exist

**Comment by dahlia** [comment]
No enough instructions to reproduce this problem.

**Comment by cdhx** [comment]
no error
just pip install wikidata

**Comment by cdhx** [comment]
maybe you need py37?

**Comment by dahlia** [comment]
I cannot reproduce this.
