### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by swedebugia** [dahlia/wikidata#15]
Hi. Is this library GPLv3 or GPLv3+ (=or later)?

**Comment by dahlia** [comment]
It's the latter case: GPL 3.0 or later.

**Comment by dahlia** [comment]
[The metadata in setup.cfg file already refers to GPLv3+.](https://github.com/dahlia/wikidata/blob/41b3592d7b5614af71573ef8a2a879248093d19f/setup.cfg#L19)
