### ISSUE TITLE
Entity.lists() is not robust to unknown locales

### ISSUE THREAD

**Issue by nelson-liu** [dahlia/wikidata#27]
See, for instance:

```
client = Client()
client.get("Q5", load=True).lists()
*** babel.core.UnknownLocaleError: unknown locale 'io'
```

I know that I can manually access all the data, but it'd be nice if `.lists()` was a bit more robust...

**Comment by dahlia** [comment]
Babel is a library for software internationalization (like translating UI messages), so its `Locale` deals with only languages listed in Unicode CLDR.  [Babel seems to have no plan to provide a way to instantiate `Locale` object with an “unknown locale.”][1]

One possible solution would be to remove Babel from this project's dependencies.  We could declare an our own distinct type instead, in the same way we declared `EntityId`:

```python
Locale = NewType('Locale', str)
```

[1]: https://github.com/python-babel/babel/issues/568#issuecomment-378350363
