### ISSUE TITLE
Except 7: time precision other than 9, 11 or 14 is unsupported wikidata

### ISSUE THREAD

**Issue by BaptisteBayche** [dahlia/wikidata#58]
Hi,

When I try to get a date with a precision level of 7, I encounter this error: `7: time precision other than 9, 11 or 14 is unsupported wikidata {'type': 'time', 'value': {'time': '+2000-00-00T00:00:00Z', 'timezone': 0, 'before': 0, 'after': 0, 'precision': 7, 'calendarmodel': 'http://www.wikidata.org/entity/Q1985727'}}`
(see https://www.wikidata.org/wiki/Q111534373 for this example)
This error occurs because precision level 7 is unsupported. However, is it possible to add support for precision 7 in datavalue.py?

I propose adding the following code at line 201:
```python
if precision == 7:
  return int(time[1:3])
```
Thank you

**Comment by dahlia** [comment]
That's a good idea! If you open a pull request, I'm going to review it as soon as possible.
